### ISSUE TITLE
Mechankiner

### ISSUE THREAD

**Issue by Mooopz** [Razor170/cec_altis_life#10]
Hatte gerade eine Idee was haltet ihr hier von: Ein Mechaniker bei dem man zum einen eine Alarmanlage in Autos einbauen kann und zum anderen eine Diebstahl Sicherung [24.11. 14:32] Razor170: Letzteres verhindert entweder das wegfahren oder den Verkauf beim chop chop [24.11. 14:32] Razor170: Ich persönlich bin für letzteres [24.11. 14:33] Razor170: Und um das Auto doch verkaufen zu können muss man es zu einem Rebellen Mechaniker bringen und dort "knacken" lassen

**Comment by Razor170** [comment]
abandoned
